import { StyleSheet } from "react-native";

import { HOME_SPACE } from "@/components/company/home/companyHomeStyles";
import {
  COMPANY_RADIUS,
  companyCardShadow,
} from "@/components/company/ui/companyDesignSystem";
import type { CompanyColorScheme } from "@/constants/companyTheme";

export function createCompanyProfileStyles(colors: CompanyColorScheme) {
  return StyleSheet.create({
    screenPad: {
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.xxxl,
    },
    pageHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: HOME_SPACE.lg,
      paddingTop: HOME_SPACE.sm,
      paddingBottom: HOME_SPACE.md,
    },
    pageTitle: {
      fontSize: 28,
      fontWeight: "800",
      color: colors.foreground,
      letterSpacing: -0.6,
    },
    pageSubtitle: {
      fontSize: 14,
      color: colors.muted,
      marginTop: 2,
      fontWeight: "500",
    },
    editBtn: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.accentSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentBorder,
    },
    editBtnText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.accent,
    },
    hero: {
      borderRadius: COMPANY_RADIUS.xl,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardBg,
      marginBottom: HOME_SPACE.lg,
      ...companyCardShadow(colors),
    },
    heroBanner: {
      height: 88,
      backgroundColor: colors.accentMuted,
    },
    heroBody: {
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.xl,
      marginTop: -36,
    },
    avatarWrap: {
      width: 80,
      height: 80,
      borderRadius: COMPANY_RADIUS.lg,
      borderWidth: 3,
      borderColor: colors.cardBg,
      backgroundColor: colors.accentSoft,
      alignItems: "center",
      justifyContent: "center",
      ...companyCardShadow(colors),
    },
    heroName: {
      fontSize: 24,
      fontWeight: "800",
      color: colors.foreground,
      letterSpacing: -0.5,
      marginTop: HOME_SPACE.md,
    },
    heroMeta: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 4,
      fontWeight: "500",
    },
    section: {
      backgroundColor: colors.cardBg,
      borderRadius: COMPANY_RADIUS.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: HOME_SPACE.lg,
      marginBottom: HOME_SPACE.md,
      ...companyCardShadow(colors),
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.foreground,
      letterSpacing: -0.2,
      marginBottom: HOME_SPACE.md,
    },
    bodyText: {
      fontSize: 15,
      lineHeight: 23,
      color: colors.textSecondary,
      fontWeight: "400",
    },
    emptyText: {
      fontSize: 14,
      lineHeight: 21,
      color: colors.muted,
      fontStyle: "italic",
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: HOME_SPACE.md,
      paddingVertical: HOME_SPACE.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    infoRowLast: {
      borderBottomWidth: 0,
    },
    infoIcon: {
      width: 40,
      height: 40,
      borderRadius: COMPANY_RADIUS.sm,
      backgroundColor: colors.accentSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    infoLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.muted,
      letterSpacing: 0.4,
      textTransform: "uppercase",
    },
    infoValue: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.foreground,
      marginTop: 2,
    },
    chipWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.accentSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentBorder,
    },
    chipText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.accentInk,
    },
    linkRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: HOME_SPACE.sm,
      paddingVertical: HOME_SPACE.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    linkOpen: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: COMPANY_RADIUS.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
    },
    linkOpenText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.accent,
    },
    noteBox: {
      marginTop: HOME_SPACE.sm,
      padding: HOME_SPACE.md,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.surfaceMuted,
    },
    noteText: {
      fontSize: 12,
      lineHeight: 18,
      color: colors.muted,
      fontWeight: "500",
    },
    stickyBar: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: HOME_SPACE.lg,
      paddingTop: HOME_SPACE.md,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.cardBg,
    },
    saveBtn: {
      backgroundColor: colors.accent,
      borderRadius: COMPANY_RADIUS.md,
      paddingVertical: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    saveBtnDisabled: {
      opacity: 0.5,
    },
    saveBtnText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },
    fieldLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.muted,
      letterSpacing: 0.4,
      marginBottom: 6,
      textTransform: "uppercase",
    },
    fieldInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.cardBg,
      paddingHorizontal: HOME_SPACE.md,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.foreground,
      marginBottom: HOME_SPACE.md,
    },
    fieldInputMultiline: {
      minHeight: 110,
      textAlignVertical: "top",
    },
  });
}
