using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraduationProject.API.Migrations
{
    /// <inheritdoc />
    public partial class AddStudentDoctorIntegrationFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE student_organization_team_members
                ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS doctor_posts (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    user_id integer NOT NULL,
                    content text NOT NULL,
                    attachment_url text,
                    attachment_type text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_doctor_posts" PRIMARY KEY (id),
                    CONSTRAINT "FK_doctor_posts_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS student_posts (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    user_id integer NOT NULL,
                    content text NOT NULL,
                    attachment_url text,
                    attachment_type text,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_student_posts" PRIMARY KEY (id),
                    CONSTRAINT "FK_student_posts_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_doctor_posts_created_at" ON doctor_posts (created_at);
                CREATE INDEX IF NOT EXISTS "IX_doctor_posts_user_id" ON doctor_posts (user_id);
                CREATE INDEX IF NOT EXISTS "IX_student_posts_created_at" ON student_posts (created_at);
                CREATE INDEX IF NOT EXISTS "IX_student_posts_user_id" ON student_posts (user_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "doctor_posts");

            migrationBuilder.DropTable(
                name: "student_posts");

            migrationBuilder.DropColumn(
                name: "display_order",
                table: "student_organization_team_members");
        }
    }
}
