using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraduationProject.API.Migrations
{
    /// <inheritdoc />
    public partial class AddPasswordResetCodes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS password_reset_codes (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    user_id integer NOT NULL,
                    email text NOT NULL,
                    code_hash text NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    expires_at timestamp with time zone NOT NULL,
                    used_at timestamp with time zone,
                    is_used boolean NOT NULL,
                    CONSTRAINT "PK_password_reset_codes" PRIMARY KEY (id),
                    CONSTRAINT "FK_password_reset_codes_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_password_reset_codes_code_hash"
                ON password_reset_codes (code_hash);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_password_reset_codes_email_is_used_expires_at"
                ON password_reset_codes (email, is_used, expires_at);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_password_reset_codes_user_id_created_at"
                ON password_reset_codes (user_id, created_at);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "password_reset_codes");
        }
    }
}
