  ai-team-invitations[m
  ai-team-selection[m
  ai-token-optimization[m
  backup-frontend-work[m
  chat-frontend-backup[m
  chat-realtime-ui[m
  clean-merge[m
  dashboard-team-invitations-sync[m
  development[m
  development-only[m
  final-integration[m
  fix-student-team-workspace-routing[m
  frontend-auth-landing-redesign[m
  frontend-clean-reset[m
* [32mfrontend-final-updates[m
  frontend-only[m
  frontend-settings-and-mobile-updates[m
  frontend-updates[m
  integration-final[m
  migration-fix[m
  mobile-ai-pages[m
  mobile-dashboard-conversion[m
  mobile-dynamic-major-skills[m
  mobile-structure-setup[m
  mobile-team-invitations-integration[m
  mobile-ui-fix[m
  my-merge-fix[m
  my-saved-work[m
  my-work-safe[m
  nitficationsandstudentassignteams[m
  notifications-system[m
  organization-event-recruitment-flow[m
  organization-event-registration-forms[m
  organization-module-web-mobile[m
  organization-recruitment-ai-flow[m
  project-updates[m
  teammate-work[m
