import { StyleSheet } from "react-native";

import { HOME_SPACE } from "@/components/company/home/companyHomeStyles";
import { COMPANY_RADIUS, companyCardShadow } from "@/components/company/ui/companyDesignSystem";
import type { CompanyColorScheme } from "@/constants/companyTheme";

export function createRequestStyles(colors: CompanyColorScheme) {
  return StyleSheet.create({
    screenPad: {
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.xxxl,
    },
    pageHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      paddingHorizontal: HOME_SPACE.lg,
      paddingTop: HOME_SPACE.sm,
      paddingBottom: HOME_SPACE.md,
      gap: HOME_SPACE.md,
    },
    pageTitle: {
      fontSize: 28,
      fontWeight: "800",
      color: colors.foreground,
      letterSpacing: -0.6,
    },
    pageSubtitle: {
      fontSize: 14,
      color: colors.muted,
      marginTop: 4,
      fontWeight: "500",
    },
    createBtn: {
      width: 44,
      height: 44,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    card: {
      backgroundColor: colors.cardBg,
      borderRadius: COMPANY_RADIUS.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: HOME_SPACE.lg,
      ...companyCardShadow(colors),
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.muted,
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    chipWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 8,
    },
    chip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.accentSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentBorder,
    },
    chipText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.accentInk,
    },
    skillChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    skillChipText: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.foreground,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: COMPANY_RADIUS.pill,
    },
    badgeText: {
      fontSize: 11,
      fontWeight: "700",
    },
    metaText: {
      fontSize: 12,
      color: colors.muted,
      fontWeight: "500",
    },
    primaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.accent,
      borderRadius: COMPANY_RADIUS.md,
      paddingVertical: 13,
      paddingHorizontal: HOME_SPACE.lg,
    },
    primaryBtnText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "700",
    },
    secondaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.cardBg,
      borderRadius: COMPANY_RADIUS.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingVertical: 13,
      paddingHorizontal: HOME_SPACE.lg,
    },
    secondaryBtnText: {
      color: colors.foreground,
      fontSize: 15,
      fontWeight: "600",
    },
    insightBox: {
      marginTop: HOME_SPACE.md,
      padding: HOME_SPACE.md,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.accentSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentBorder,
    },
    insightTitle: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.accent,
      marginBottom: 6,
    },
    insightLine: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textSecondary,
      marginTop: 2,
    },
    statGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: HOME_SPACE.sm,
      paddingHorizontal: HOME_SPACE.lg,
      marginBottom: HOME_SPACE.lg,
    },
    statCard: {
      flex: 1,
      minWidth: "46%",
      backgroundColor: colors.cardBg,
      borderRadius: COMPANY_RADIUS.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: HOME_SPACE.md,
      ...companyCardShadow(colors),
    },
    statValue: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.foreground,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: "600",
      color: colors.muted,
      marginTop: 2,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    heroTitle: {
      fontSize: 24,
      fontWeight: "800",
      color: colors.foreground,
      letterSpacing: -0.4,
      lineHeight: 30,
    },
    heroDesc: {
      fontSize: 15,
      lineHeight: 22,
      color: colors.textSecondary,
      marginTop: HOME_SPACE.sm,
    },
    specRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    specLabel: {
      fontSize: 13,
      color: colors.muted,
      fontWeight: "500",
    },
    specValue: {
      fontSize: 14,
      color: colors.foreground,
      fontWeight: "600",
      flex: 1,
      textAlign: "right",
      marginLeft: HOME_SPACE.md,
    },
  });
}
