import type { CSSProperties } from "react";

export const doctorPageStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(155deg,#f8f7ff 0%,#f0f4ff 40%,#faf5ff 100%)",
    fontFamily: "DM Sans, sans-serif",
    color: "#0f172a",
    display: "flex",
    flexDirection: "column",
  },
  nav: {
    flexShrink: 0,
    background: "rgba(248,247,255,0.92)",
    backdropFilter: "blur(20px)",
    borderBottom: "1px solid rgba(99,102,241,0.1)",
  },
  navInner: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "0 24px",
    minHeight: 62,
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  navLogo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    textDecoration: "none",
    marginRight: 8,
    flexShrink: 0,
  },
  logoIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 9,
    background: "linear-gradient(135deg,#6366f1,#a855f7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 12px rgba(99,102,241,0.3)",
  },
  logoText: {
    fontSize: 18,
    fontWeight: 800,
    color: "#0f172a",
    fontFamily: "Syne, sans-serif",
  },
  logoAccent: {
    background: "linear-gradient(135deg,#6366f1,#a855f7)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    marginLeft: "auto",
  },
  navBtn: {
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "none",
    color: "#64748b",
    cursor: "pointer",
    borderRadius: 8,
    textDecoration: "none",
  },
  navAvatar: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    overflow: "hidden",
    cursor: "pointer",
    marginLeft: 4,
    textDecoration: "none",
    flexShrink: 0,
  },
  navAvatarFallback: {
    width: "100%",
    height: "100%",
    background: "linear-gradient(135deg,#6366f1,#a855f7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 800,
    color: "#fff",
  },
  mainGrid: {
    flex: 1,
    maxWidth: 1280,
    margin: "0 auto",
    width: "100%",
    padding: "24px 24px 48px",
    display: "grid",
    gridTemplateColumns: "minmax(200px, 240px) minmax(0, 1fr)",
    gap: 24,
    alignItems: "start",
    boxSizing: "border-box",
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    position: "sticky",
    top: 78,
  },
  sideNavBtn: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1.5px solid transparent",
    background: "transparent",
    color: "#64748b",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    width: "100%",
    transition: "background 0.18s ease, border-color 0.18s ease, color 0.18s ease",
  },
  sideNavBtnActive: {
    background: "white",
    borderColor: "#c7d2fe",
    color: "#4338ca",
    boxShadow: "0 2px 12px rgba(99,102,241,0.08)",
  },
  contentCol: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  sectionPanel: {
    opacity: 1,
    transition: "opacity 0.2s ease",
  },
  sectionPanelHidden: {
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    width: 0,
    height: 0,
    overflow: "hidden",
  },
  hero: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 24,
    padding: "24px 28px",
    background: "white",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 20,
    boxShadow: "0 4px 24px rgba(99,102,241,0.06)",
    flexWrap: "wrap",
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#0f172a",
    margin: "0 0 6px",
    letterSpacing: "-0.5px",
    fontFamily: "Syne, sans-serif",
    lineHeight: 1.2,
  },
  heroSub: {
    fontSize: 14,
    color: "#64748b",
    margin: "0 0 8px",
    fontWeight: 500,
  },
  heroMeta: { fontSize: 13, color: "#94a3b8", margin: 0 },
  heroStats: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 10,
    flexShrink: 0,
    minWidth: 0,
    flex: "1 1 280px",
    maxWidth: 520,
  },
  statCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "#eef2ff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: "#6366f1",
  },
  statValue: {
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a",
    margin: "0 0 2px",
    fontFamily: "Syne, sans-serif",
  },
  statLabel: { fontSize: 10, color: "#94a3b8", margin: 0, fontWeight: 500 },
  card: {
    background: "white",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: "18px",
    boxShadow: "0 2px 12px rgba(99,102,241,0.04)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    flexWrap: "wrap",
    gap: 8,
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "#64748b",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: 6,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "28px 16px",
    gap: 8,
    textAlign: "center",
  },
  emptyTitle: { fontSize: 14, fontWeight: 700, color: "#475569", margin: 0 },
  emptyDesc: {
    fontSize: 12,
    color: "#94a3b8",
    margin: 0,
    maxWidth: 320,
    lineHeight: 1.6,
  },
  acceptBtn: {
    padding: "7px 14px",
    borderRadius: 8,
    border: "none",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    background: "linear-gradient(135deg,#6366f1,#a855f7)",
    color: "white",
  },
  rejectBtn: {
    padding: "7px 14px",
    borderRadius: 8,
    border: "1.5px solid #e2e8f0",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    background: "white",
    color: "#64748b",
  },
  skillBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: 999,
    background: "#eef2ff",
    color: "#4338ca",
    border: "1px solid #c7d2fe",
  },
  removeBtn: {
    padding: "8px 14px",
    borderRadius: 10,
    border: "1.5px solid #fecaca",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    background: "white",
    color: "#b91c1c",
  },
};
