using GraduationProject.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GraduationProject.API.Services
{
    /// <summary>
    /// Ensures Communication Hub tables exist when the manual migration was not applied via EF.
    /// </summary>
    public static class CommunicationFeedSchemaStartupRepair
    {
        public static async Task RunAsync(ApplicationDbContext db, ILogger logger)
        {
            const string sql = """
                CREATE TABLE IF NOT EXISTS company_follows (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_profile_id integer NOT NULL,
                    student_profile_id integer NOT NULL,
                    followed_at timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_company_follows_company_profiles_company_profile_id"
                        FOREIGN KEY (company_profile_id) REFERENCES company_profiles (id) ON DELETE CASCADE,
                    CONSTRAINT "FK_company_follows_student_profiles_student_profile_id"
                        FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_company_follows_company_profile_id_student_profile_id"
                    ON company_follows (company_profile_id, student_profile_id);

                CREATE INDEX IF NOT EXISTS "IX_company_follows_student_profile_id"
                    ON company_follows (student_profile_id);

                CREATE TABLE IF NOT EXISTS feed_post_engagements (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    post_key text NOT NULL,
                    engagement_type text NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_feed_post_engagements_users_user_id"
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_feed_post_engagements_user_id_post_key_engagement_type"
                    ON feed_post_engagements (user_id, post_key, engagement_type);

                CREATE INDEX IF NOT EXISTS "IX_feed_post_engagements_post_key"
                    ON feed_post_engagements (post_key);

                CREATE TABLE IF NOT EXISTS feed_post_comments (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    post_key text NOT NULL,
                    content text NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_feed_post_comments_users_user_id"
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_feed_post_comments_post_key"
                    ON feed_post_comments (post_key);

                CREATE INDEX IF NOT EXISTS "IX_feed_post_comments_user_id"
                    ON feed_post_comments (user_id);

                CREATE TABLE IF NOT EXISTS student_posts (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    content text NOT NULL,
                    attachment_url text NULL,
                    attachment_type text NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_student_posts_users_user_id"
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );

                ALTER TABLE student_posts ADD COLUMN IF NOT EXISTS attachment_url text NULL;
                ALTER TABLE student_posts ADD COLUMN IF NOT EXISTS attachment_type text NULL;

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'student_posts' AND column_name = 'image_url'
                    ) THEN
                        UPDATE student_posts
                        SET attachment_url = image_url,
                            attachment_type = 'Image'
                        WHERE attachment_url IS NULL AND image_url IS NOT NULL;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_student_posts_user_id"
                    ON student_posts (user_id);

                CREATE INDEX IF NOT EXISTS "IX_student_posts_created_at"
                    ON student_posts (created_at);

                CREATE TABLE IF NOT EXISTS doctor_posts (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id integer NOT NULL,
                    content text NOT NULL,
                    attachment_url text NULL,
                    attachment_type text NULL,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_doctor_posts_users_user_id"
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_doctor_posts_user_id"
                    ON doctor_posts (user_id);

                CREATE INDEX IF NOT EXISTS "IX_doctor_posts_created_at"
                    ON doctor_posts (created_at);
                """;

            try
            {
                await db.Database.ExecuteSqlRawAsync(sql);
                logger.LogInformation("Communication feed schema repair completed (company_follows, feed_post_*)");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Communication feed schema repair failed");
                throw;
            }
        }
    }
}
