import type { CSSProperties } from "react";

const wrap: CSSProperties = {
  overflowWrap: "anywhere",
  wordBreak: "break-word",
};

export const aiPanelStyles: Record<string, CSSProperties> = {
  groupShell: {
    marginTop: 16,
    borderRadius: 16,
    border: "1px solid rgba(99,102,241,0.16)",
    background:
      "linear-gradient(165deg, rgba(99,102,241,0.06) 0%, rgba(255,255,255,0.98) 42%, #ffffff 100%)",
    boxShadow: "0 8px 28px rgba(99,102,241,0.08)",
    overflow: "hidden",
  },
  section: {
    padding: "16px 16px 14px",
  },
  sectionDivider: {
    borderTop: "1px solid rgba(99,102,241,0.1)",
  },
  blockHeader: { marginBottom: 12 },
  blockTitleRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
  },
  iconWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 10,
    background:
      "linear-gradient(135deg,rgba(99,102,241,0.14),rgba(168,85,247,0.1))",
    border: "1px solid rgba(99,102,241,0.2)",
    flexShrink: 0,
  },
  blockTitle: {
    margin: 0,
    fontSize: 10,
    fontWeight: 800,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  blockSub: {
    margin: "4px 0 0",
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 1.5,
    maxWidth: 520,
    ...wrap,
  },
  actionsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "9px 16px",
    borderRadius: 10,
    border: "none",
    background: "linear-gradient(135deg,#6366f1,#a855f7)",
    color: "white",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 4px 14px rgba(99,102,241,0.32)",
    minWidth: 200,
  },
  primaryBtnDisabled: {
    opacity: 0.65,
    cursor: "not-allowed",
    boxShadow: "none",
  },
  collapseToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 12px",
    borderRadius: 10,
    border: "1px solid rgba(99,102,241,0.22)",
    background: "rgba(255,255,255,0.85)",
    color: "#6366f1",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  resultsBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 12,
    padding: "10px 12px",
    borderRadius: 12,
    background: "rgba(99,102,241,0.06)",
    border: "1px solid rgba(99,102,241,0.12)",
  },
  resultsBarLabel: {
    margin: 0,
    fontSize: 12,
    fontWeight: 700,
    color: "#475569",
  },
  resultsBarMeta: {
    margin: "2px 0 0",
    fontSize: 11,
    color: "#94a3b8",
  },
  hintMuted: {
    margin: "0 0 12px",
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 1.55,
    ...wrap,
  },
  spinIcon: {
    animation: "aiPanelSpin 0.8s linear infinite",
  },
  loadingBox: {
    marginTop: 14,
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "14px 16px",
    background:
      "linear-gradient(135deg,rgba(99,102,241,0.07),rgba(168,85,247,0.05))",
    border: "1px solid rgba(99,102,241,0.15)",
    borderRadius: 14,
    boxSizing: "border-box",
    minHeight: 72,
  },
  loadingTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 700,
    color: "#334155",
  },
  loadingSub: {
    margin: "4px 0 0",
    fontSize: 11,
    color: "#94a3b8",
    lineHeight: 1.45,
  },
  errorBox: {
    marginTop: 14,
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "14px 16px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 14,
    boxSizing: "border-box",
    minHeight: 72,
  },
  errorTitle: {
    margin: "0 0 4px",
    fontSize: 12,
    fontWeight: 800,
    color: "#b91c1c",
  },
  errorBody: {
    margin: 0,
    fontSize: 12,
    color: "#64748b",
    lineHeight: 1.55,
    ...wrap,
  },
  emptyBox: {
    marginTop: 14,
    textAlign: "center",
    padding: "22px 18px",
    background: "#f8fafc",
    border: "1px dashed #cbd5e1",
    borderRadius: 14,
    boxSizing: "border-box",
    minHeight: 100,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    margin: "10px 0 6px",
    fontSize: 13,
    fontWeight: 700,
    color: "#475569",
  },
  emptyDesc: {
    margin: 0,
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 1.55,
    maxWidth: 320,
    ...wrap,
  },
  resultsBody: {
    marginTop: 10,
  },
};

export const AI_PANEL_SPIN_KEYFRAMES = `
  @keyframes aiPanelSpin { to { transform: rotate(360deg); } }
`;
