import { StyleSheet } from "react-native";
import { radius, spacing } from "@/constants/responsiveLayout";

export const aiPanelStyles = StyleSheet.create({
  groupShell: {
    marginTop: spacing.lg,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.16)",
    backgroundColor: "#fff",
    overflow: "hidden",
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  section: {
    padding: spacing.md,
    paddingBottom: spacing.md,
  },
  sectionDivider: {
    borderTopWidth: 1,
    borderTopColor: "rgba(99,102,241,0.1)",
  },
  blockHeader: { marginBottom: spacing.md },
  blockTitleRow: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  blockTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: "#64748b",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  blockSub: {
    marginTop: 4,
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 18,
    maxWidth: 320,
  },
  actionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: 4,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
    backgroundColor: "#7c3aed",
    minWidth: 200,
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 2,
  },
  primaryBtnDisabled: { opacity: 0.6 },
  primaryBtnText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  collapseBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.22)",
    backgroundColor: "rgba(255,255,255,0.95)",
  },
  collapseBtnText: { color: "#6366f1", fontSize: 12, fontWeight: "700" },
  hintMuted: {
    fontSize: 12,
    color: "#94a3b8",
    lineHeight: 18,
    marginBottom: spacing.sm,
  },
  loadingBox: {
    marginTop: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.15)",
    backgroundColor: "rgba(99,102,241,0.06)",
  },
  loadingTitle: { fontSize: 13, fontWeight: "700", color: "#334155" },
  loadingSub: { marginTop: 4, fontSize: 11, color: "#94a3b8" },
  errorBox: {
    marginTop: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fef2f2",
  },
  errorTitle: { fontSize: 12, fontWeight: "800", color: "#b91c1c", marginBottom: 4 },
  errorBody: { fontSize: 12, color: "#64748b", lineHeight: 18, flex: 1 },
  emptyBox: {
    marginTop: spacing.md,
    alignItems: "center",
    padding: spacing.lg,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
  },
  emptyTitle: { fontSize: 13, fontWeight: "700", color: "#475569", marginTop: spacing.sm },
  emptyDesc: {
    fontSize: 12,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 6,
    maxWidth: 300,
  },
  resultsBar: {
    marginTop: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    padding: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 12,
    backgroundColor: "rgba(99,102,241,0.06)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
  },
  resultsBarLabel: { fontSize: 12, fontWeight: "700", color: "#475569" },
  resultsBarMeta: { marginTop: 2, fontSize: 11, color: "#94a3b8" },
  resultsBody: { marginTop: spacing.sm },
  cardList: { gap: spacing.sm },
  recCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  recCardBest: {
    borderColor: "rgba(34,197,94,0.35)",
  },
  bestAccentBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: "#22c55e",
  },
  recCardInner: { padding: spacing.md, paddingLeft: spacing.md + 4 },
  recCardTop: { flexDirection: "row", gap: spacing.sm, alignItems: "flex-start" },
  rankCol: { gap: 6 },
  rankBadge: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748b",
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  rankBadgeBest: { backgroundColor: "#dcfce7", color: "#15803d" },
  bestBadge: { fontSize: 10, fontWeight: "700", color: "#15803d" },
  recMain: { flex: 1, minWidth: 0 },
  recName: { fontSize: 14, fontWeight: "700", color: "#0f172a" },
  recMeta: { marginTop: 4, fontSize: 12, color: "#64748b", lineHeight: 18 },
  recSpec: { marginTop: 4, fontSize: 12, color: "#64748b", lineHeight: 18 },
  scoreRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  scoreLabel: { fontSize: 11, fontWeight: "600", color: "#94a3b8" },
  scoreValue: { fontSize: 13, fontWeight: "800", color: "#6366f1" },
  scoreValueBest: { color: "#15803d" },
  skillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginTop: spacing.sm },
  reasonBlock: {
    marginTop: spacing.sm,
    padding: spacing.sm,
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  reasonLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#94a3b8",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  reason: { fontSize: 12, color: "#475569", lineHeight: 18, fontStyle: "italic" },
  actionRow: { marginTop: spacing.md, alignItems: "flex-end" },
  inviteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#c7d2fe",
    backgroundColor: "#fff",
  },
  inviteBtnDisabled: { opacity: 0.55 },
  inviteBtnText: { color: "#6366f1", fontSize: 12, fontWeight: "700" },
  requestBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: "#6366f1",
  },
  requestBtnText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  requestBtnDisabled: { opacity: 0.6 },
  outlineLink: {
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "#c7d2fe",
    alignSelf: "flex-start",
  },
  outlineLinkText: { color: "#6366f1", fontWeight: "700", fontSize: 12 },
  statusText: { fontSize: 11, fontWeight: "600", color: "#64748b", marginTop: spacing.sm },
  statusOk: { color: "#15803d", fontWeight: "700" },
});
