-- Repair script: team recommendation tables missing while migration history exists.
-- Safe to re-run (IF NOT EXISTS). Execute in pgAdmin against skillswap_db.

CREATE TABLE IF NOT EXISTS company_request_team_recommendation_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_request_id integer NOT NULL REFERENCES company_requests(id) ON DELETE CASCADE,
    company_profile_id integer NOT NULL REFERENCES company_profiles(id) ON DELETE CASCADE,
    algorithm_version character varying(64) NOT NULL,
    status character varying(24) NOT NULL DEFAULT 'completed',
    generated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NULL,
    error_message character varying(2000) NULL
);

CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_runs_company_profile_id"
    ON company_request_team_recommendation_runs (company_profile_id);
CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_runs_company_request_id"
    ON company_request_team_recommendation_runs (company_request_id);
CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_runs_company_request_id~"
    ON company_request_team_recommendation_runs (company_request_id, generated_at);

CREATE TABLE IF NOT EXISTS company_request_team_recommendations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id integer NOT NULL REFERENCES company_request_team_recommendation_runs(id) ON DELETE CASCADE,
    company_request_id integer NOT NULL REFERENCES company_requests(id) ON DELETE CASCADE,
    team_rank integer NOT NULL,
    total_score integer NOT NULL,
    role_coverage_score integer NOT NULL,
    compatibility_score integer NOT NULL,
    summary_reason character varying(2000) NOT NULL,
    strengths_json character varying(4000) NULL,
    risks_json character varying(4000) NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendations_company_request_id"
    ON company_request_team_recommendations (company_request_id);
CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendations_run_id"
    ON company_request_team_recommendations (run_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_company_request_team_recommendations_run_id_team_rank"
    ON company_request_team_recommendations (run_id, team_rank);

CREATE TABLE IF NOT EXISTS company_request_team_recommendation_members (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_recommendation_id integer NOT NULL REFERENCES company_request_team_recommendations(id) ON DELETE CASCADE,
    company_request_role_id integer NOT NULL REFERENCES company_request_roles(id) ON DELETE CASCADE,
    student_profile_id integer NOT NULL REFERENCES student_profiles(id) ON DELETE CASCADE,
    role_score integer NOT NULL,
    semantic_similarity double precision NOT NULL,
    assignment_reason character varying(2000) NOT NULL,
    highlights_json character varying(4000) NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_members_company_request~"
    ON company_request_team_recommendation_members (company_request_role_id);
CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_members_student_profile~"
    ON company_request_team_recommendation_members (student_profile_id);
CREATE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_members_team_recommenda~"
    ON company_request_team_recommendation_members (team_recommendation_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_company_request_team_recommendation_members_team_recommenda~1"
    ON company_request_team_recommendation_members (team_recommendation_id, company_request_role_id);
