import type { CSSProperties } from 'react'
import { assocDash } from '../association/dashboard/associationDashTokens'

export const hub = {
  page: {
    minHeight: '100vh',
    background: `linear-gradient(165deg, ${assocDash.bg} 0%, #eef2f7 48%, #f8fafc 100%)`,
    fontFamily: assocDash.font,
    color: assocDash.text,
  } satisfies CSSProperties,
  shell: {
    maxWidth: 1040,
    margin: '0 auto',
    padding: '0 20px 56px',
  } satisfies CSSProperties,
  hero: {
    marginTop: 8,
    marginBottom: 28,
    padding: '28px 28px 26px',
    borderRadius: 20,
    border: `1px solid ${assocDash.accentBorder}`,
    background: `linear-gradient(135deg, ${assocDash.accentMuted} 0%, #fff 55%, #f8fafc 100%)`,
    boxShadow: '0 12px 40px rgba(217, 119, 6, 0.08)',
    position: 'relative',
    overflow: 'hidden',
  } satisfies CSSProperties,
  heroGlow: {
    position: 'absolute',
    top: -40,
    right: -20,
    width: 180,
    height: 180,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(245,158,11,0.22) 0%, transparent 70%)',
    pointerEvents: 'none',
  } satisfies CSSProperties,
  heroTitle: {
    margin: 0,
    fontSize: 28,
    fontWeight: 800,
    fontFamily: assocDash.fontDisplay,
    color: assocDash.text,
    letterSpacing: '-0.02em',
  } satisfies CSSProperties,
  heroSubtitle: {
    margin: '10px 0 0',
    fontSize: 15,
    lineHeight: 1.55,
    color: assocDash.muted,
    maxWidth: 560,
  } satisfies CSSProperties,
  section: {
    marginBottom: 32,
  } satisfies CSSProperties,
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  } satisfies CSSProperties,
  sectionTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
    fontFamily: assocDash.fontDisplay,
    color: assocDash.text,
  } satisfies CSSProperties,
  sectionHint: {
    margin: 0,
    fontSize: 13,
    color: assocDash.muted,
  } satisfies CSSProperties,
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 18,
  } satisfies CSSProperties,
  searchWrap: {
    flex: '1 1 240px',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '11px 14px',
    borderRadius: 12,
    border: `1px solid ${assocDash.border}`,
    background: '#fff',
    boxShadow: '0 2px 8px rgba(15,23,42,0.04)',
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    border: 'none',
    outline: 'none',
    fontSize: 14,
    fontFamily: 'inherit',
    background: 'transparent',
    color: assocDash.text,
  } satisfies CSSProperties,
  select: {
    flex: '0 1 190px',
    padding: '11px 12px',
    borderRadius: 12,
    border: `1px solid ${assocDash.border}`,
    background: '#fff',
    fontSize: 14,
    fontFamily: 'inherit',
    color: assocDash.text,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(15,23,42,0.04)',
  } satisfies CSSProperties,
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  } satisfies CSSProperties,
  chip: (active: boolean): CSSProperties => ({
    padding: '7px 14px',
    borderRadius: 999,
    border: `1px solid ${active ? assocDash.accentBorder : assocDash.border}`,
    background: active ? assocDash.accentMuted : '#fff',
    color: active ? assocDash.accentDark : assocDash.muted,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 16,
  } satisfies CSSProperties,
  horizontalRow: {
    display: 'flex',
    gap: 14,
    overflowX: 'auto',
    paddingBottom: 6,
    scrollSnapType: 'x mandatory',
  } satisfies CSSProperties,
  horizontalCardWrap: {
    flex: '0 0 280px',
    scrollSnapAlign: 'start',
  } satisfies CSSProperties,
  empty: {
    padding: '36px 24px',
    borderRadius: 16,
    border: `1px dashed ${assocDash.border}`,
    background: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
  } satisfies CSSProperties,
  emptyIcon: {
    width: 56,
    height: 56,
    margin: '0 auto 14px',
    borderRadius: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: assocDash.accentMuted,
    color: assocDash.accent,
  } satisfies CSSProperties,
  ctaBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
    padding: '10px 18px',
    borderRadius: 10,
    background: assocDash.accent,
    color: '#fff',
    fontSize: 13,
    fontWeight: 700,
    textDecoration: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
  } satisfies CSSProperties,
}
