-- Run in pgAdmin if "dotnet ef database update" cannot run (e.g. API process locking build).
-- Creates company_talent_requests and records the migration.

CREATE TABLE IF NOT EXISTS company_talent_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_profile_id integer NOT NULL REFERENCES company_profiles(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text NOT NULL,
    required_skills text,
    preferred_major text,
    engagement_type text,
    duration text,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS "IX_company_talent_requests_company_profile_id"
    ON company_talent_requests (company_profile_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260517180000_AddCompanyTalentRequests', '8.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260517180000_AddCompanyTalentRequests'
);
