SELECT 'users' AS entity, u.id, u.email, u.role FROM users u WHERE u.email LIKE '%+e2e@%' ORDER BY u.email;
SELECT 'company_profiles' AS entity, cp.id, cp.company_name, cp.user_id FROM company_profiles cp WHERE cp.normalized_company_name = 'helix martin systems';
SELECT 'company_members' AS entity, cm.id, cm.user_id, cm.company_profile_id, cm.role FROM company_members cm JOIN company_profiles cp ON cp.id = cm.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems';
SELECT 'student_profiles' AS entity, sp.id, u.email FROM student_profiles sp JOIN users u ON u.id = sp.user_id WHERE u.email LIKE '%+e2e@metrosu.edu' ORDER BY u.email;
SELECT 'company_requests' AS entity, cr.id, cr.title, cr.status, cr.request_status FROM company_requests cr JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems' ORDER BY cr.id;
SELECT 'recommendation_runs' AS entity, r.id, r.company_request_id, cr.title FROM company_request_recommendation_runs r JOIN company_requests cr ON cr.id = r.company_request_id JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems';
SELECT 'recommendations' AS entity, rec.id, rec.run_id, rec.rank, rec.student_profile_id, rec.score FROM company_request_recommendations rec JOIN company_requests cr ON cr.id = rec.company_request_id JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems' ORDER BY rec.run_id, rec.rank;
SELECT 'team_recommendations' AS entity, tr.id, tr.run_id, tr.team_rank, tr.total_score FROM company_request_team_recommendations tr JOIN company_requests cr ON cr.id = tr.company_request_id JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems';
SELECT 'invitations' AS entity, i.id, i.company_request_id, i.student_profile_id, i.status FROM company_request_invitations i JOIN company_profiles cp ON cp.id = i.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems' ORDER BY i.id;
SELECT 'notifications' AS entity, n.id, n.user_id, u.email, n.event_type, n.project_id FROM user_notifications n JOIN users u ON u.id = n.user_id WHERE u.email LIKE '%+e2e@helixmartin.com' AND n.category = 'company' ORDER BY n.id;
SELECT
  (SELECT COUNT(*) FROM company_requests cr JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems') AS requests_count,
  (SELECT COUNT(*) FROM company_request_recommendations rec JOIN company_requests cr ON cr.id = rec.company_request_id JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems') AS individual_recommendations_count,
  (SELECT COUNT(*) FROM company_request_team_recommendations tr JOIN company_requests cr ON cr.id = tr.company_request_id JOIN company_profiles cp ON cp.id = cr.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems') AS team_recommendations_count,
  (SELECT COUNT(*) FROM company_request_invitations i JOIN company_profiles cp ON cp.id = i.company_profile_id WHERE cp.normalized_company_name = 'helix martin systems') AS invitations_count,
  (SELECT COUNT(*) FROM user_notifications n JOIN users u ON u.id = n.user_id WHERE u.email LIKE '%+e2e@helixmartin.com' AND n.category = 'company') AS notifications_count;
