import { StyleSheet } from "react-native";

import { HOME_SPACE } from "@/components/company/home/companyHomeStyles";
import { COMPANY_RADIUS } from "@/components/company/ui/companyDesignSystem";
import type { CompanyColorScheme } from "@/constants/companyTheme";

export function createWizardStyles(colors: CompanyColorScheme) {
  return StyleSheet.create({
    progressWrap: {
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.md,
      gap: 8,
    },
    progressMeta: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    progressLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.foreground,
    },
    progressStep: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.muted,
    },
    progressTrack: {
      height: 6,
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.surfaceMuted,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: COMPANY_RADIUS.pill,
      backgroundColor: colors.accent,
    },
    draftMeta: {
      fontSize: 12,
      color: colors.muted,
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.sm,
    },
    content: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: HOME_SPACE.lg,
      paddingBottom: HOME_SPACE.md,
      gap: HOME_SPACE.md,
    },
    stepTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.foreground,
      letterSpacing: -0.4,
    },
    stepSubtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      marginTop: 4,
    },
    errorBanner: {
      marginHorizontal: HOME_SPACE.lg,
      marginBottom: HOME_SPACE.sm,
      padding: HOME_SPACE.md,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.pausedMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.warning,
    },
    errorText: {
      fontSize: 13,
      color: "#DC2626",
      fontWeight: "600",
    },
    footer: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.cardBg,
      paddingHorizontal: HOME_SPACE.lg,
      paddingTop: HOME_SPACE.md,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: HOME_SPACE.md,
    },
    footerReview: {
      flexDirection: "column",
      alignItems: "stretch",
      gap: HOME_SPACE.sm,
    },
    backBtn: {
      paddingVertical: 12,
      paddingHorizontal: 4,
      minHeight: 48,
      justifyContent: "center",
    },
    backBtnText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.foreground,
    },
    primaryBtn: {
      flex: 1,
      minHeight: 48,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: HOME_SPACE.lg,
    },
    primaryBtnDisabled: {
      opacity: 0.45,
    },
    primaryBtnText: {
      fontSize: 15,
      fontWeight: "800",
      color: "#FFFFFF",
    },
    outlineBtn: {
      minHeight: 48,
      borderRadius: COMPANY_RADIUS.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardBg,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: HOME_SPACE.lg,
    },
    outlineBtnText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.foreground,
    },
    fieldLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.foreground,
      marginBottom: 8,
    },
    required: {
      color: "#DC2626",
    },
    input: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: COMPANY_RADIUS.md,
      paddingHorizontal: HOME_SPACE.md,
      paddingVertical: 12,
      fontSize: 16,
      color: colors.foreground,
      backgroundColor: colors.cardBg,
    },
    inputMultiline: {
      minHeight: 120,
      textAlignVertical: "top",
    },
    selectTrigger: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: COMPANY_RADIUS.md,
      paddingHorizontal: HOME_SPACE.md,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: colors.cardBg,
    },
    selectValue: {
      flex: 1,
      fontSize: 16,
      color: colors.foreground,
    },
    selectPlaceholder: {
      flex: 1,
      fontSize: 16,
      color: colors.muted,
    },
    typeCard: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: COMPANY_RADIUS.lg,
      padding: HOME_SPACE.lg,
      flexDirection: "row",
      gap: HOME_SPACE.md,
      backgroundColor: colors.cardBg,
    },
    typeCardSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.accentSoft,
    },
    typeIcon: {
      width: 48,
      height: 48,
      borderRadius: COMPANY_RADIUS.md,
      backgroundColor: colors.accentSoft,
      alignItems: "center",
      justifyContent: "center",
    },
    typeTitle: {
      fontSize: 16,
      fontWeight: "800",
      color: colors.foreground,
    },
    typeDesc: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
      marginTop: 4,
    },
    roleCard: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: COMPANY_RADIUS.lg,
      padding: HOME_SPACE.lg,
      backgroundColor: colors.cardBg,
      gap: HOME_SPACE.md,
    },
    roleCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    roleBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    roleBadgeText: {
      fontSize: 13,
      fontWeight: "800",
      color: "#FFFFFF",
    },
    addRoleBtn: {
      minHeight: 48,
      borderRadius: COMPANY_RADIUS.md,
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: colors.accentBorder,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
      backgroundColor: colors.accentSoft,
    },
    addRoleText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.accent,
    },
    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 48,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.cardBg,
    },
    checkboxChecked: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    checkboxLabel: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.foreground,
      flex: 1,
    },
    successIcon: {
      width: 72,
      height: 72,
      borderRadius: COMPANY_RADIUS.lg,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
    },
    successActions: {
      gap: HOME_SPACE.sm,
      marginTop: HOME_SPACE.xl,
    },
  });
}
