import type { CSSProperties } from 'react'
import { assocDash } from '../association/dashboard/associationDashTokens'
import { hub } from '../organizations/organizationHubStyles'

export { hub }

export const communitiesHub = {
  portalHero: {
    marginTop: 8,
    marginBottom: 36,
    padding: '40px 36px 36px',
    borderRadius: 24,
    border: `1px solid ${assocDash.accentBorder}`,
    background: `linear-gradient(145deg, #fffbeb 0%, #ffffff 42%, #f1f5f9 100%)`,
    boxShadow: '0 16px 48px rgba(217, 119, 6, 0.1)',
    position: 'relative',
    overflow: 'hidden',
  } satisfies CSSProperties,
  heroOrb1: {
    position: 'absolute',
    top: -60,
    right: -30,
    width: 220,
    height: 220,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(245,158,11,0.28) 0%, transparent 68%)',
    pointerEvents: 'none',
  } satisfies CSSProperties,
  heroOrb2: {
    position: 'absolute',
    bottom: -80,
    left: -40,
    width: 200,
    height: 200,
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(99,102,241,0.12) 0%, transparent 70%)',
    pointerEvents: 'none',
  } satisfies CSSProperties,
  heroOrb3: {
    position: 'absolute',
    top: '40%',
    right: '18%',
    width: 80,
    height: 80,
    borderRadius: 16,
    background: 'linear-gradient(135deg, rgba(251,191,36,0.35), rgba(251,146,60,0.15))',
    transform: 'rotate(12deg)',
    pointerEvents: 'none',
  } satisfies CSSProperties,
  portalTitle: {
    margin: 0,
    fontSize: 34,
    fontWeight: 800,
    fontFamily: assocDash.fontDisplay,
    color: assocDash.text,
    letterSpacing: '-0.03em',
    lineHeight: 1.15,
  } satisfies CSSProperties,
  portalSubtitle: {
    margin: '14px 0 0',
    fontSize: 16,
    lineHeight: 1.6,
    color: assocDash.muted,
    maxWidth: 580,
  } satisfies CSSProperties,
  featureGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 18,
    marginBottom: 40,
  } satisfies CSSProperties,
  featureCard: {
    display: 'flex',
    flexDirection: 'column',
    padding: '22px 22px 20px',
    borderRadius: 18,
    border: `1px solid ${assocDash.border}`,
    background: '#fff',
    boxShadow: '0 6px 24px rgba(15,23,42,0.06)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease',
    minHeight: 200,
  } satisfies CSSProperties,
  featureIcon: (accent: string): CSSProperties => ({
    width: 44,
    height: 44,
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: accent,
    marginBottom: 16,
  }),
  featureTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
    fontFamily: assocDash.fontDisplay,
    color: assocDash.text,
  } satisfies CSSProperties,
  featureDesc: {
    margin: '8px 0 0',
    fontSize: 13,
    lineHeight: 1.5,
    color: assocDash.muted,
    flex: 1,
  } satisfies CSSProperties,
  comingSoonBadge: {
    display: 'inline-block',
    marginTop: 10,
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    background: '#f1f5f9',
    color: '#64748b',
    border: `1px solid ${assocDash.border}`,
  } satisfies CSSProperties,
  featureBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    padding: '11px 16px',
    borderRadius: 10,
    border: 'none',
    background: assocDash.accent,
    color: '#fff',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textDecoration: 'none',
    transition: 'background 0.15s ease, transform 0.15s ease',
  } satisfies CSSProperties,
  featureBtnSecondary: {
    background: '#fff',
    color: assocDash.accentDark,
    border: `1px solid ${assocDash.accentBorder}`,
  } satisfies CSSProperties,
  previewSection: {
    marginTop: 8,
  } satisfies CSSProperties,
  previewCard: {
    flex: '0 0 260px',
    scrollSnapAlign: 'start',
    padding: 16,
    borderRadius: 14,
    border: `1px solid ${assocDash.border}`,
    background: '#fff',
    boxShadow: '0 4px 16px rgba(15,23,42,0.05)',
  } satisfies CSSProperties,
}
